//
// Created by ilya on 17.05.18.
//

#ifndef IO_MULTIPLEXING_CONSTANTS_AND_TYPES_H
#define IO_MULTIPLEXING_CONSTANTS_AND_TYPES_H

#include <cstddef>

const size_t BUFFER_SIZE = 2048;
#endif //IO_MULTIPLEXING_CONSTANTS_AND_TYPES_H
